name: eventmanagement
description: A new Flutter application.
version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  http: ^0.12.2
  flutter_bloc: ^6.1.1
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4
  string_validator: ^0.1.4
  path_provider: ^1.6.1
  path: ^1.6.4
  network_to_file_image: ^2.3.6
  image_picker: ^0.6.5+3
  video_player: ^1.0.1
  video_thumbnail: 0.2.5+1
  url_launcher: ^5.4.5
  fluttertoast: ^7.1.5
  webview_flutter: ^1.0.5
  flutter_inappwebview: ^4.0.0+4
  html_editor:
    git:
      url: git://github.com/vikalpnagar/flutter-html-editor.git
      ref: master
  file_picker: ^2.1.4
  barcode_scan: ^3.0.1
  flutter_nfc_reader: ^0.1.0
  synchronized: 2.2.0+2
  video_compress: ^2.1.1
  open_file: ^3.0.3
#  flutter_downloader: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.2
  intl_translation: ^0.17.7
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/carnivalist_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_bold.ttf
        - asset: assets/fonts/montserrat_medium.ttf
        - asset: assets/fonts/montserrat_regular.ttf
    - family:  CarnivalistIcons
      fonts:
        - asset: assets/fonts/CarnivalistIcons.ttf