name: eventmanagement
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  intl:
  http:
  flutter_bloc:
  provider:
  shared_preferences:
  string_validator: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.7.2
  intl_translation: ^0.17.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_bold.ttf
        - asset: assets/fonts/montserrat_medium.ttf
        - asset: assets/fonts/montserrat_regular.ttf